version: '3'

services:
    ros2-fast-dds-discovery-server:
        image: galactic-ros-desktop-go:1.16.2
        environment:
            RMW_IMPLEMENTATION: rmw_fastrtps_cpp
        command: fastdds discovery -i 0 -l 172.25.0.3 -p 11811
        restart: always
        networks:
            docker-mac-network_default:
                ipv4_address: 172.25.0.3
networks:
    docker-mac-network_default:
        external: true